---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: default
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: system/applications
    repoURL: https://github.com/modzilla99/k8s-infra
    targetRevision: HEAD
  syncPolicy:
    automated: {}
status: {}
