---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  project: default
  source:
    path: system/sealed-secrets
    repoURL: https://github.com/modzilla99/k8s-infra
    targetRevision: HEAD
  syncPolicy:
    automated: {}
status: {}