---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
    app: webhook-hetzner
    app.kubernetes.io/instance: cert-manager
  name: cert-manager-webhook-hetzner-apikey
  namespace: cert-manager
spec:
  encryptedData:
    apiKey: AgAMgH1C2jvzoRGc/N+8MLYXnSSz8ralZc35iCi5201u1dlXoXkqUMzo8vzi8Knrastpe++CxzZJ43nX8i6MavHTuU2dD5nO5qc+1N8XsxrexVkGFTtznr43R6jwOza5qRYzW1Qcqv3Fo/3/lem8Js7f5g94caRAxQObzhwOHJ07xu402R5jXrJkOziFjdY2z6Tf0Rk/wSpPSuv7wRo69+wmu4TdrY32DxQYqz5xPobI24uNp2UllIl5xUObHHuaUbTwizHdnyTC2QFq6+WEajG8t+gOK82xfihEeFO1+9VCsXahjSCmq9LEIdguSOdSF6/X0MM//0InlGvvXqdoJDVflH5JKzW/Amvuc9K7P/p4HgASOY4rBIAGG0QnOzkMo6IL91Fo/EzYY+pE+8FE9+OLRS3LCljIxfVoZqZa3IfTLGWoAEVvU39XIzQ3eLAiiRCqtuE+Y22Y2mMpvp4k4plI1U9DcbRdW4d55cMDxxAT0noKR03pGbZSdZku22yfbOgr9RzjSKQd8p6qdn+mjT89pzwG0fy/HElEQ5OVl8pVNQXjRtnpLAMceL1OqU3KRNkWH/issxITJUERY25qrV92U0v1OslLpZzhRXGAh0ZahtLGOppTkONvfwBZsu0tBboi0poNfKRA4xZOIHUtIEz8p5wDOsxFnKG1IoBVnOjZJ7N+KYOSoawxq1OKHm0ZSXE1kiJr+qsoGxLGU8chKua9oW7yusjGBVfxSwT2m7B6/w==
  template:
    metadata:
      labels:
        app: webhook-hetzner
        app.kubernetes.io/instance: cert-manager
      name: cert-manager-webhook-hetzner-apikey
      namespace: cert-manager
    type: Opaque
