resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.16.1/cert-manager.yaml
  - cert-manager-webhook-hetzner.yml
  - cert-manager-webhook-hetzner-apikey.yaml
  - clusterissuer.yaml
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: cert-manager
        namespace: cert-manager
      spec:
        template:
          spec:
            dnsPolicy: "None"
            dnsConfig:
              nameservers:
                - 8.8.8.8
                - 8.8.4.4