---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: all-certificates
  namespace: projectcontour
spec:
  commonName: "modlab.cloud"
  dnsNames:
    - "modlab.cloud"
    - "k8s.modlab.cloud"
    - "m0dz1lla.de"
    - "jlamp.eu"
    - "*.modlab.cloud"
    - "*.k8s.modlab.cloud"
    - "*.m0dz1lla.de"
    - "*.jlamp.eu"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: all-certificates