resources:
  - https://github.com/sergelogvinov/proxmox-csi-plugin/raw/v0.7.0/docs/deploy/proxmox-csi-plugin-release.yml
  - cloud-config.yaml
  - storageclasses.yaml
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: proxmox-csi-plugin-node
        namespace: csi-proxmox
      spec:
        template:
          spec:
            containers:
            - name: csi-node-driver-registrar
              args:
                - '-v=5'
                - '--csi-address=unix:///csi/csi.sock'
                - '--kubelet-registration-path=/var/lib/k0s/kubelet/plugins/csi.proxmox.sinextra.dev/csi.sock'
            - name: proxmox-csi-plugin-node
              volumeMounts:
              - name: kubelet
                mountPath: /var/lib/k0s/kubelet
                mountPropagation: Bidirectional
            volumes:
            - name: socket
              hostPath:
                path: /var/lib/k0s/kubelet/plugins/csi.proxmox.sinextra.dev/
                type: DirectoryOrCreate
            - name: registration
              hostPath:
                path: /var/lib/k0s/kubelet/plugins_registry/
                type: Directory
            - name: kubelet
              hostPath:
                path: /var/lib/k0s/kubelet
                type: Directory
