---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/component: route
    app.kubernetes.io/name: argocd-route
    app.kubernetes.io/part-of: argocd
  name: argocd
  namespace: argocd
spec:
  hostnames:
  - argocd.k8s.modlab.cloud
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: default
    namespace: projectcontour
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: argocd-server
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/component: route
    app.kubernetes.io/name: argocd-route
    app.kubernetes.io/part-of: argocd
  name: argocd
  namespace: argocd
spec:
  hostnames:
  - argocd.k8s.modlab.cloud
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: default
    namespace: projectcontour
    sectionName: https
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: argocd-server
      port: 80
      weight: 1
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GRPCRoute
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/component: route
    app.kubernetes.io/name: argocd-route
    app.kubernetes.io/part-of: argocd
  name: argocd
  namespace: argocd
spec:
  hostnames:
  - argocd-grpc.k8s.modlab.cloud
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: default
    namespace: projectcontour
    sectionName: https
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: argocd-server
      port: 80
      weight: 1
    matches:
    - headers: 
      - type: Exact
        name: Content-Type
        value: "application/grpc"